### ISSUE TITLE
Mount License Mathpass in Dockerfile

### ISSUE THREAD

**Issue by AndyxuNTU** [davecwright3/jupyter-mathematica#2]
Still there any way to mount the License key inside the dockerfile instead of running it from the command terminal?

Look forward to hear from you soon!

**Comment by davecwright3** [comment]
After you log in with your wolfram credentials, you could commit the changes you've made to the container in order to save the state of the container including the license key.
https://docs.docker.com/engine/reference/commandline/commit/
